# Generated by Django 4.2.24 on 2025-10-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('player_name', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('level', models.IntegerField(default=1)),
                ('time_played', models.IntegerField(default=0)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'ordering': ['-score', '-date'],
            },
        ),
    ]
